version: '2'
services:
    merlion-app:
        image: merlion
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://merlion-mysql:3306/merlion?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=merlion-elasticsearch:9300
        ports:
            - 8080:8080
    merlion-mysql:
        extends:
            file: mysql.yml
            service: merlion-mysql
    merlion-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: merlion-elasticsearch
